version: "3"

services:

  nginx:
    # Add basic auth both to the webui and the remote driver connection
    build:
      context: ./auth
    ports:
      - 4444:80
    depends_on:
      - selenium-hub
    environment:
      - FORWARD_HOST=selenium-hub
      - FORWARD_PORT=4444
      - BASIC_USERNAME=testuser
      - BASIC_PASSWORD=password

  chrome-0:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4  # will not go above the cpu count of the host

  chrome-1:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4  # will not go above the cpu count of the host

  # firefox:
  #   image: selenium/node-firefox:latest
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #     - SE_NODE_MAX_SESSIONS=4

  # edge:
  #   image: selenium/node-edge:latest
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #     - SE_NODE_MAX_SESSIONS=4

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    # ports:
      # - "4442:4442"
      # - "4443:4443"
      # - "4444:4444"
